/*
 * File: app/model/Anesthesia_Vitals.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Procedures.model.Anesthesia_Vitals', {
    extend: 'Ext.data.Model',
    alias: 'model.anesthesia_vitals',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'ID'
        },
        {
            mapping: 'encounter_nr',
            name: 'encounter_nr'
        },
        {
            mapping: 'item_description',
            name: 'item_description'
        },
        {
            mapping: 1,
            name: '1'
        },
        {
            mapping: 2,
            name: '2'
        },
        {
            mapping: 3,
            name: '3'
        },
        {
            mapping: 4,
            name: '4'
        },
        {
            mapping: 5,
            name: '5'
        },
        {
            mapping: 6,
            name: '6'
        },
        {
            mapping: 7,
            name: '7'
        },
        {
            mapping: 8,
            name: '8'
        },
        {
            mapping: 9,
            name: '9'
        },
        {
            mapping: 10,
            name: '10'
        },
        {
            mapping: 11,
            name: '11'
        },
        {
            mapping: 12,
            name: '12'
        },
        {
            mapping: 13,
            name: '13'
        },
        {
            mapping: 14,
            name: '14'
        },
        {
            mapping: 15,
            name: '15'
        },
        {
            mapping: 16,
            name: '16'
        },
        {
            mapping: 17,
            name: '17'
        },
        {
            mapping: 18,
            name: '18'
        },
        {
            mapping: 19,
            name: '19'
        },
        {
            mapping: 20,
            name: '20'
        },
        {
            mapping: 21,
            name: '21'
        },
        {
            mapping: 22,
            name: '22'
        },
        {
            mapping: 23,
            name: '23'
        },
        {
            mapping: 24,
            name: '24'
        }
    ]
});