/*
 * File: app/model/PatientDetails.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Procedures.model.PatientDetails', {
    extend: 'Ext.data.Model',
    alias: 'model.patientdetails',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'pid'
        },
        {
            name: 'selian_pid'
        },
        {
            name: 'pnames'
        },
        {
            name: 'date_birth'
        },
        {
            name: 'sex'
        },
        {
            mapping: 'encounter_nr',
            name: 'encounter_nr'
        }
    ]
});