/*
 * File: app/store/WardInfoStore.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.store.WardInfoStore', {
    extend: 'Ext.data.Store',
    alias: 'store.wardinforstore',

    requires: [
        'CarePortal.model.WardInfo',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'WardInfoStore',
            autoLoad: true,
            model: 'CarePortal.model.WardInfo',
            proxy: {
                type: 'ajax',
                url: 'data/getDataFunctions.php?task=getWardInfo',
                reader: {
                    type: 'json',
                    rootProperty: 'Wards'
                }
            }
        }, cfg)]);
    }
});