/*
 * File: app/view/CashPointsList.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.CashPointsList', {
    extend: 'Ext.form.Panel',
    alias: 'widget.cashpointslist',

    requires: [
        'CarePortal.view.CashPointsListViewModel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'cashpoints'
    },
    height: 687,
    width: 798,
    layout: 'absolute',
    bodyPadding: 10,
    title: 'Cash Points',

    items: [
        {
            xtype: 'textfield',
            x: 5,
            y: 5,
            itemId: 'cashpoint',
            fieldLabel: 'Cash Point',
            name: 'CashPoint'
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 75,
            itemId: 'prefix',
            fieldLabel: 'Prefix',
            name: 'Prefix'
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 40,
            itemId: 'description',
            fieldLabel: 'Description',
            name: 'Description'
        },
        {
            xtype: 'button',
            x: 145,
            y: 110,
            itemId: 'save',
            width: 95,
            text: 'Save'
        },
        {
            xtype: 'button',
            x: 260,
            y: 110,
            itemId: 'refresh',
            text: 'Reset'
        },
        {
            xtype: 'button',
            x: 5,
            y: 545,
            itemId: 'deletecashpoint',
            text: 'Delete Cash Point'
        },
        {
            xtype: 'gridpanel',
            x: 5,
            y: 145,
            height: 395,
            title: 'My Grid Panel',
            bind: {
                store: '{cashPointsModels}'
            },
            viewConfig: {
                width: 733
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'code',
                    text: 'Code'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'prefix',
                    text: 'Prefix'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nextreceiptNo',
                    text: 'Nextreceipt No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nextvoucherNo',
                    text: 'Nextvoucher No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nextshiftNo',
                    text: 'Nextshift No'
                }
            ]
        }
    ]

});