/*
 * File: app/view/InsuranceCredit.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.InsuranceCredit', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.insurancecredit',

    requires: [
        'CarePortal.view.InsuranceCreditViewModel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'insurancecredit'
    },
    animateShadow: true,
    shadow: true,
    shadowOffset: 20,
    border: true,
    height: 380,
    width: 675,
    layout: 'absolute',
    bodyBorder: true,
    bodyStyle: 'background:#84b3cc',
    frameHeader: false,
    titleAlign: 'center',

    items: [
        {
            xtype: 'textfield',
            x: 55,
            y: 15,
            itemId: 'creditNo',
            width: 190,
            fieldLabel: 'Credit No',
            labelAlign: 'right',
            labelWidth: 70,
            name: 'creditNo',
            readOnly: true
        },
        {
            xtype: 'textfield',
            x: 450,
            y: 10,
            hidden: true,
            itemId: 'formType',
            width: 175,
            fieldLabel: 'FormType',
            labelAlign: 'right',
            labelWidth: 70,
            name: 'creditName'
        },
        {
            xtype: 'textfield',
            x: 55,
            y: 50,
            tabIndex: 1,
            itemId: 'txtPid2',
            width: 190,
            fieldLabel: 'PID',
            labelAlign: 'right',
            labelWidth: 70,
            name: 'pid'
        },
        {
            xtype: 'textfield',
            x: 420,
            y: 80,
            itemId: 'encounterNr',
            width: 205,
            fieldLabel: 'Encounter No',
            labelAlign: 'right',
            name: 'encounterNr'
        },
        {
            xtype: 'textfield',
            x: 355,
            y: 205,
            itemId: 'days',
            width: 190,
            fieldLabel: 'Days',
            labelAlign: 'right',
            labelWidth: 70,
            name: 'days'
        },
        {
            xtype: 'combobox',
            x: 55,
            y: 80,
            tabIndex: 2,
            itemId: 'billNumber',
            width: 290,
            fieldLabel: 'Invoice No',
            labelAlign: 'right',
            labelWidth: 70,
            name: 'billNumber',
            displayField: 'BillNumbers',
            typeAhead: true,
            valueField: 'BillNumbers'
        },
        {
            xtype: 'textfield',
            x: 325,
            y: 240,
            itemId: 'invoiceAmount',
            width: 260,
            fieldLabel: 'Invoice Amount',
            labelAlign: 'right',
            name: 'invoiceAmount'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 240,
            tabIndex: 6,
            itemId: 'creditAmount',
            width: 255,
            fieldLabel: 'Credit Amount',
            labelAlign: 'right',
            name: 'creditAmount'
        },
        {
            xtype: 'textfield',
            x: 55,
            y: 270,
            draggable: true,
            itemId: 'balance',
            width: 225,
            fieldLabel: 'Balance',
            labelAlign: 'right',
            labelWidth: 70,
            name: 'balance'
        },
        {
            xtype: 'datefield',
            x: 25,
            y: 180,
            tabIndex: 3,
            itemId: 'admissionDate',
            width: 300,
            fieldLabel: 'Admission Date',
            labelAlign: 'right',
            name: 'admissionDate'
        },
        {
            xtype: 'datefield',
            x: 25,
            y: 205,
            tabIndex: 5,
            itemId: 'releaseDate',
            width: 300,
            fieldLabel: 'Release Date',
            labelAlign: 'right',
            name: 'releaseDate'
        },
        {
            xtype: 'datefield',
            x: 325,
            y: 180,
            tabIndex: 4,
            itemId: 'dischargeDate',
            width: 300,
            fieldLabel: 'Discharge Date',
            labelAlign: 'right',
            name: 'dischargeDate'
        },
        {
            xtype: 'combobox',
            x: 5,
            y: 115,
            tabIndex: 2,
            itemId: 'accno',
            width: 420,
            fieldLabel: 'Insurance Account',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'accno',
            displayField: 'Description',
            minChars: 2,
            queryMode: 'local',
            store: 'InsuranceCompaniesStore',
            typeAhead: true,
            valueField: 'Accno'
        },
        {
            xtype: 'textfield',
            x: 245,
            y: 50,
            itemId: 'pname',
            width: 380,
            labelWidth: 70,
            name: 'pname'
        },
        {
            xtype: 'checkboxfield',
            x: 275,
            y: 15,
            name: 'isNHIF',
            boxLabel: 'Does the Patient have NHIF'
        },
        {
            xtype: 'button',
            x: 180,
            y: 305,
            tabIndex: 7,
            height: 40,
            itemId: 'cmdSave',
            width: 105,
            text: 'Save'
        },
        {
            xtype: 'button',
            x: 420,
            y: 305,
            tabIndex: 8,
            height: 40,
            itemId: 'cmdClose',
            width: 105,
            text: 'Close'
        }
    ]

});