/*
 * File: app/view/OpdVisits.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.OpdVisits', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.opdvisits',

    requires: [
        'CarePortal.view.OpdVisitsViewModel',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    config: {
        isPortlet: true
    },

    viewModel: {
        type: 'opdvisits'
    },
    cls: 'x-portlet',
    draggable: {
        moveOnDrag: false
    },
    itemId: 'clinics',
    closable: true,
    collapsible: true,
    title: 'Outpatient Clinics Statistics',

    items: [
        {
            xtype: 'dataview',
            height: 179,
            tpl: [
                '<table class="clinics" border=0 width="100%">',
                '    <tr><td class="clinics">Clinic</td><td class="clinics">TotalPatients</td>',
                '        <td class="clinics">Males</td><td class="clinics">Females</td>',
                '        <td class="clinics">Below 5</td><td class="clinics">Above 5</td></tr>',
                '    <tpl for=".">',
                '        <tpl><tr>',
                '            <td class="clinics">{Clinic}</td><td class="clinics">{TotalPatients}</td>',
                '            <td class="clinics">{Males}</td><td class="clinics">{Females}</td>',
                '            <td class="clinics">{Below5}</td><td class="clinics">{Above5}</td></tr>',
                '        </tpl>',
                '    </tpl>',
                '</table>',
                '<div class="x-clear"></div>'
            ],
            itemSelector: 'div.SelectedClinicsValues',
            store: 'ClinicInfoStore'
        }
    ]

});