/*
 * File: app/view/Payments.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Payments', {
    extend: 'Ext.form.Panel',
    alias: 'widget.payments',

    requires: [
        'CarePortal.view.PaymentsViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'payments'
    },
    height: 489,
    width: 815,
    layout: 'absolute',
    bodyPadding: 10,

    items: [
        {
            xtype: 'textfield',
            x: 5,
            y: 40,
            itemId: 'paymentmode',
            width: 210,
            fieldLabel: 'Payment Mode',
            name: 'PaymentMode'
        },
        {
            xtype: 'combobox',
            x: 5,
            y: 75,
            itemId: 'glaccount',
            width: 210,
            fieldLabel: 'GL Account ',
            name: 'GLAccount'
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 110,
            itemId: 'payeetoward',
            width: 450,
            fieldLabel: 'Payee Toward',
            name: 'PayeeToward'
        },
        {
            xtype: 'textfield',
            x: 215,
            y: 40,
            width: 240
        },
        {
            xtype: 'textfield',
            x: 215,
            y: 75,
            width: 240
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 5,
            itemId: 'vouchernumber',
            fieldLabel: 'Voucher No:',
            name: 'VoucherNumber'
        },
        {
            xtype: 'textfield',
            x: 485,
            y: 5,
            itemId: 'date',
            fieldLabel: 'Date',
            labelAlign: 'right',
            name: 'Date'
        },
        {
            xtype: 'textfield',
            x: 485,
            y: 40,
            itemId: 'cheque',
            fieldLabel: 'Cheque',
            labelAlign: 'right',
            name: 'Cheque'
        },
        {
            xtype: 'textfield',
            x: 485,
            y: 75,
            itemId: 'control',
            fieldLabel: 'Control',
            labelAlign: 'right',
            name: 'Control'
        },
        {
            xtype: 'textfield',
            x: 330,
            y: 410,
            itemId: 'total',
            width: 255,
            fieldLabel: 'Total',
            labelAlign: 'right',
            name: 'Total'
        },
        {
            xtype: 'button',
            x: 435,
            y: 450,
            itemId: 'save',
            width: 145,
            text: 'Save'
        },
        {
            xtype: 'gridpanel',
            x: 5,
            y: 145,
            height: 260,
            title: 'My Grid Panel',
            columnLines: true,
            store: 'LedgeStore',
            viewConfig: {
                height: 101
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ledger',
                    text: 'Ledger'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'code',
                    text: 'Code'
                },
                {
                    xtype: 'gridcolumn',
                    width: 274,
                    dataIndex: 'name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'amount',
                    text: 'Amount'
                }
            ]
        }
    ]

});