/*
 * File: app/view/SyncData.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hha.view.SyncData', {
    extend: 'Ext.form.Panel',
    alias: 'widget.syncdata',

    requires: [
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.form.field.TextArea'
    ],

    frame: true,
    layout: 'absolute',
    bodyPadding: 10,
    collapsible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 10,
                    itemId: 'ServerAddress',
                    width: 320,
                    fieldLabel: 'Server Address'
                },
                {
                    xtype: 'datefield',
                    x: 20,
                    y: 35,
                    itemId: 'StartDate',
                    fieldLabel: 'Start Date'
                },
                {
                    xtype: 'datefield',
                    x: 20,
                    y: 60,
                    itemId: 'EndDate',
                    fieldLabel: 'End Date'
                },
                {
                    xtype: 'button',
                    x: 125,
                    y: 90,
                    itemId: 'cmdPreviewJson',
                    width: 115,
                    text: '<b>Preview Json Data</b>'
                },
                {
                    xtype: 'button',
                    x: 295,
                    y: 90,
                    itemId: 'cmdSendJson',
                    width: 115,
                    text: '<b>Send  Data</b>'
                },
                {
                    xtype: 'textareafield',
                    x: 5,
                    y: 120,
                    height: '',
                    itemId: 'JsonData',
                    minHeight: 400,
                    minWidth: 690,
                    width: '',
                    name: 'JsonData'
                }
            ]
        });

        me.callParent(arguments);
    }

});