/*
 * File: app/view/Clinics.js
 * Date: Mon Mar 09 2020 09:46:08 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.view.Clinics', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.clinics',

    requires: [
        'ReportsMain.view.ClinicsViewModel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'clinics'
    },
    height: 615,
    resizable: true,
    closable: true,
    icon: '../../icons/fam/grid.png',
    title: 'List of Clinic Numbers',
    columnLines: true,
    store: 'ClinicsStore',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'ClinicsStore'
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'datefield',
                    itemId: 'startDate',
                    fieldLabel: 'Start Date',
                    labelWidth: 65,
                    altFormats: 'Y-m-d',
                    format: 'Y-m-d',
                    submitFormat: 'Y-m-d'
                },
                {
                    xtype: 'datefield',
                    itemId: 'endDate',
                    fieldLabel: 'End Date',
                    labelWidth: 60,
                    altFormats: 'Y-m-d',
                    format: 'Y-m-d',
                    submitFormat: 'Y-d-m'
                },
                {
                    xtype: 'button',
                    height: 25,
                    itemId: 'cmdSearchClinics',
                    width: 110,
                    text: '<b>Preview</b>'
                },
                {
                    xtype: 'button',
                    height: 25,
                    itemId: 'cmdPrint',
                    width: 100,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    height: 25,
                    itemId: 'cmdExportClinics',
                    width: 115,
                    text: '<b>Export To Excel</b>'
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'RevenueCode',
            text: 'Revenue Code'
        },
        {
            xtype: 'gridcolumn',
            width: 196,
            dataIndex: 'Description',
            text: 'Description'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Count',
            text: 'Count'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Ext.util.Format.number(value, '0.00');
            },
            align: 'end',
            dataIndex: 'Total',
            formatter: 'round(2)',
            text: 'Total'
        }
    ]

});