/*
 * File: app/view/LabTests.js
 * Date: Mon Mar 09 2020 09:46:08 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.view.LabTests', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.labtests',

    requires: [
        'ReportsMain.view.LabTestsViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate',
        'Ext.form.field.Date',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'labtests'
    },
    height: 615,
    resizable: true,
    closable: true,
    icon: '../../icons/fam/grid.png',
    title: 'Lab Tests',
    columnLines: true,
    store: 'LabTestsStore',

    columns: [
        {
            xtype: 'gridcolumn',
            summaryRenderer: function(val, params, data) {
                return ((val===0 || val>1)?'('+val+' Tests)':'(1 Test)');
            },
            summaryType: 'count',
            width: 151,
            dataIndex: 'Group',
            text: 'Group'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ItemID',
            text: 'Item Id'
        },
        {
            xtype: 'gridcolumn',
            width: 234,
            dataIndex: 'Description',
            text: 'Description'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            align: 'center',
            dataIndex: 'Male',
            text: 'Male'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            align: 'center',
            dataIndex: 'Female',
            text: 'Female'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            align: 'center',
            dataIndex: 'Total',
            groupable: false,
            text: 'Total'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            align: 'center',
            dataIndex: 'Below5',
            text: '< 5 yrs'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            align: 'center',
            dataIndex: 'Between5And14',
            text: '5 - 14 yrs'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            align: 'center',
            dataIndex: 'Above14',
            text: '> 14 yrs'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'LabTestsStore'
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'datefield',
                    itemId: 'startDate',
                    fieldLabel: 'Start Date',
                    labelWidth: 65,
                    altFormats: 'Y-m-d',
                    format: 'Y-m-d',
                    submitFormat: 'Y-m-d'
                },
                {
                    xtype: 'datefield',
                    itemId: 'endDate',
                    fieldLabel: 'End Date',
                    labelWidth: 60,
                    format: 'Y-m-d',
                    submitFormat: 'Y-d-m'
                },
                {
                    xtype: 'button',
                    height: 25,
                    itemId: 'cmdSearch',
                    width: 110,
                    text: '<b>Preview</b>'
                },
                {
                    xtype: 'button',
                    height: 25,
                    itemId: 'cmdPrint',
                    width: 100,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    height: 25,
                    itemId: 'cmdExportToExcel',
                    width: 115,
                    text: '<b>Export To Excel</b>'
                }
            ]
        }
    ],
    features: [
        {
            ftype: 'grouping',
            groupHeaderTpl: [
                '{columnName}: {name}'
            ]
        }
    ]

});