/*
 * File: app/view/MyGridPanel1.js
 * Date: Tue Aug 02 2011 16:19:42 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.0 Beta1.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('app.view.MyGridPanel1', {
  extend: 'app.view.ui.MyGridPanel1',

  initComponent: function() {
    var me = this;
    me.callParent(arguments);
  }
});