/*
 * File: app/view/OpVisits.js
 * Date: Thu May 21 2020 09:09:10 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.view.OpVisits', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.opvisits',

    requires: [
        'ReportsMain.view.OpVisitsViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.feature.GroupingSummary',
        'Ext.XTemplate',
        'Ext.form.field.Date',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'opvisits'
    },
    height: 615,
    closable: true,
    title: 'Monthly Workload',
    columnLines: true,
    store: 'OpVisitsStore',

    columns: [
        {
            xtype: 'gridcolumn',
            summaryType: 'count',
            hidden: true,
            dataIndex: 'parent',
            groupable: true,
            text: 'Parent'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'opCode',
            groupable: true,
            text: 'Op Code'
        },
        {
            xtype: 'gridcolumn',
            summaryRenderer: function(val, params, data) {
                return ((val === 0 || val > 1) ? '(' + val + ' Results)' : '(Total Patients)');
            },
            width: 270,
            dataIndex: 'Description',
            groupable: true,
            tdCls: 'opdesc',
            text: 'Description'
        },
        {
            xtype: 'numbercolumn',
            summaryType: 'sum',
            dataIndex: 'New',
            text: 'New',
            format: '0'
        },
        {
            xtype: 'numbercolumn',
            summaryType: 'sum',
            dataIndex: 'Ret',
            text: 'Return',
            format: '0'
        },
        {
            xtype: 'numbercolumn',
            summaryType: 'sum',
            dataIndex: 'Total',
            text: 'Total',
            format: '0'
        }
    ],
    features: [
        {
            ftype: 'groupingsummary',
            groupHeaderTpl: [
                '{columnName}: {name}'
            ],
            showGroupsText: 'Return reults'
        }
    ],
    dockedItems: [
        {
            xtype: 'container',
            dock: 'top',
            height: 43,
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'datefield',
                    x: 0,
                    y: 5,
                    itemId: 'startDate',
                    fieldLabel: 'Start Date',
                    labelAlign: 'right',
                    labelStyle: 'font-weight:bold;color:green;',
                    labelWidth: 80,
                    format: 'Y-m-d'
                },
                {
                    xtype: 'datefield',
                    x: 265,
                    y: 5,
                    itemId: 'endDate',
                    fieldLabel: 'End Date',
                    labelAlign: 'right',
                    labelStyle: 'font-weight:bold;color:green;',
                    labelWidth: 80,
                    format: 'Y-m-d'
                },
                {
                    xtype: 'button',
                    x: 530,
                    y: 5,
                    itemId: 'cmdPreviewVisits',
                    width: 110,
                    iconCls: 'x-fa fa-search',
                    text: '<b>Preview</b>'
                },
                {
                    xtype: 'button',
                    x: 650,
                    y: 5,
                    itemId: 'cmdExportVisits',
                    width: 110,
                    iconCls: 'x-fa fa-share-square-o',
                    text: '<b>Export</b>'
                },
                {
                    xtype: 'button',
                    x: 770,
                    y: 5,
                    itemId: 'cmdPrintVisits',
                    width: 115,
                    iconCls: 'x-fa fa-print',
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    x: 895,
                    y: 5,
                    itemId: 'cmdUpdateReport',
                    width: 145,
                    iconCls: 'x-fa fa-plus',
                    text: '<b>Update Report</b>'
                }
            ]
        }
    ]

});