/*
 * File: app/model/ReceiptsAllocate.js
 * Date: Mon Aug 16 2021 14:09:45 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Debtors.model.ReceiptsAllocate', {
    extend: 'Ext.data.Model',
    alias: 'model.receiptsallocate',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            mapping: 'transno',
            name: 'transno'
        },
        {
            mapping: 'accno',
            name: 'accno'
        },
        {
            mapping: 'debtorname',
            name: 'debtorname'
        },
        {
            name: 'pid'
        },
        {
            name: 'memberNo'
        },
        {
            name: 'pname'
        },
        {
            name: 'bill_number'
        },
        {
            mapping: 'transdate',
            name: 'transdate'
        },
        {
            mapping: 'InvoiceAmount',
            name: 'InvoiceAmount'
        },
        {
            mapping: 'AllocatedAmount',
            name: 'AllocatedAmount'
        }
    ]
});