/*
 * File: app/model/LabTests.js
 * Date: Mon Oct 22 2018 10:41:59 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.model.LabTests', {
    extend: 'Ext.data.Model',
    alias: 'model.labtests',

    requires: [
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            name: 'Group'
        },
        {
            name: 'ItemID'
        },
        {
            name: 'Description'
        },
        {
            type: 'int',
            name: 'Male'
        },
        {
            type: 'int',
            name: 'Female'
        },
        {
            type: 'int',
            name: 'Total'
        },
        {
            type: 'int',
            name: 'Below5'
        },
        {
            type: 'int',
            name: 'Between5And14'
        },
        {
            type: 'int',
            name: 'Above14'
        }
    ]
});