/*
 * File: app/model/OpMobidityModel.js
 * Date: Mon Oct 22 2018 10:41:59 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.model.OpMobidityModel', {
    extend: 'Ext.data.Model',
    alias: 'model.opmobidity',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            mapping: 'icdCode',
            name: 'icdCode'
        },
        {
            mapping: 'disease',
            name: 'disease'
        },
        {
            mapping: '1',
            name: '1'
        },
        {
            mapping: '2',
            name: '2'
        },
        {
            mapping: '3',
            name: '3'
        },
        {
            mapping: '4',
            name: '4'
        },
        {
            mapping: '5',
            name: '5'
        },
        {
            mapping: '6',
            name: '6'
        },
        {
            mapping: '7',
            name: '7'
        },
        {
            mapping: '8',
            name: '8'
        },
        {
            mapping: '9',
            name: '9'
        },
        {
            mapping: '10',
            name: '10'
        },
        {
            mapping: '11',
            name: '11'
        },
        {
            mapping: '12',
            name: '12'
        },
        {
            mapping: '13',
            name: '13'
        },
        {
            mapping: '14',
            name: '14'
        },
        {
            mapping: '15',
            name: '15'
        },
        {
            mapping: '16',
            name: '16'
        },
        {
            mapping: '17',
            name: '17'
        },
        {
            mapping: '18',
            name: '18'
        },
        {
            mapping: '19',
            name: '19'
        },
        {
            mapping: '20',
            name: '20'
        },
        {
            mapping: '21',
            name: '21'
        },
        {
            mapping: '22',
            name: '22'
        },
        {
            mapping: '23',
            name: '23'
        },
        {
            mapping: '24',
            name: '24'
        },
        {
            mapping: '25',
            name: '25'
        },
        {
            mapping: '26',
            name: '26'
        },
        {
            mapping: '27',
            name: '27'
        },
        {
            mapping: '28',
            name: '28'
        },
        {
            mapping: '29',
            name: '29'
        },
        {
            mapping: '30',
            name: '30'
        },
        {
            mapping: '31',
            name: '31'
        },
        {
            name: 'TOTALS'
        }
    ]
});