/*
 * File: app/view/Portal.js
 * Date: Mon May 18 2020 11:00:01 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Portal', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.portal',

    requires: [
        'CarePortal.view.PortalViewModel',
        'CarePortal.view.OutpatientList',
        'CarePortal.view.PortalPanel',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'portal'
    },

    layout: {
        type: 'border',
        padding: '0 5 5 5'
    },
    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            id: 'app-options',
            maxWidth: 400,
            minWidth: 250,
            width: 365,
            collapsible: true,
            title: 'Options',
            layout: {
                type: 'accordion',
                animate: true
            },
            items: [
                {
                    xtype: 'panel',
                    height: 417,
                    scrollable: true,
                    iconCls: 'nav',
                    title: 'Navigation',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            height: 119,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mnuHome',
                                    text: '<span style="color: green; font-size:small;">Home</span>',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mnuNursingArea',
                                    icon: '../icons/triage.png',
                                    text: '<span style="color: green; font-size:small;">Triage</span>',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mnuDoctorsArea',
                                    icon: '../icons/doctors.png',
                                    text: '<span style=" color: green; font-size:small;">Doctors Rooms</span>',
                                    focusable: true
                                }
                            ]
                        },
                        {
                            xtype: 'outpatientlist'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            region: 'center',
            itemId: 'PortalDetails',
            items: [
                {
                    xtype: 'portalpanel'
                }
            ]
        }
    ]

});