/*
 * File: app/store/DepartmentStore.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Requisition.store.DepartmentStore', {
    extend: 'Ext.data.Store',
    alias: 'store.departmentstore',

    requires: [
        'Requisition.model.Departments',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 200,
            storeId: 'DepartmentStore',
            autoLoad: true,
            autoSync: true,
            model: 'Requisition.model.Departments',
            proxy: {
                type: 'ajax',
                url: 'data/getDataFunctions.php?task=getDepartments',
                reader: {
                    type: 'json',
                    rootProperty: 'departments'
                }
            }
        }, cfg)]);
    }
});