/*
 * File: app/view/BookingForm.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Procedures.view.BookingForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.bookingform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.HtmlEditor',
        'Ext.button.Button'
    ],

    frame: true,
    height: 590,
    width: 813,
    layout: 'absolute',
    bodyPadding: 10,
    url: '../data/getDataFunctions.php?task=createBooking',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: '../data/getDataFunctions.php?task=createBooking'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    x: -3,
                    y: 30,
                    height: 200,
                    width: 410,
                    title: 'Patient Info',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'pid',
                            width: 245,
                            fieldLabel: 'Pid',
                            name: 'pid',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'selian_pid',
                            width: 244,
                            fieldLabel: 'File no',
                            name: 'selian_pid',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'pnames',
                            width: 355,
                            fieldLabel: 'Names',
                            name: 'pnames',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'date_birth',
                            width: 244,
                            fieldLabel: 'Date of Birth',
                            name: 'date_birth',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            id: 'sex',
                            width: 244,
                            fieldLabel: 'Gender',
                            name: 'sex',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            width: 367,
                            fieldLabel: 'Allergies',
                            name: 'allergies'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    x: 410,
                    y: 30,
                    height: 200,
                    width: 380,
                    title: 'Surgeons',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 319,
                            fieldLabel: 'Surgeon',
                            name: 'surgeon',
                            allowBlank: false,
                            blankText: 'Surgeon is required',
                            displayField: 'staff_name',
                            minChars: 1,
                            store: 'StaffStore',
                            valueField: 'ID'
                        },
                        {
                            xtype: 'combobox',
                            width: 319,
                            fieldLabel: 'Asst. Surgeon',
                            name: 'asst_surgeon',
                            displayField: 'staff_name',
                            minChars: 1,
                            store: 'StaffStore',
                            valueField: 'ID'
                        },
                        {
                            xtype: 'combobox',
                            width: 354,
                            fieldLabel: 'Planned Surgery',
                            name: 'procedure_type',
                            displayField: 'item_description',
                            minChars: 3,
                            store: 'ProcedureNamesStore',
                            valueField: 'partcode'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Procedure Date',
                            name: 'procedure_date',
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    x: 0,
                    y: 230,
                    height: 180,
                    width: 430,
                    layout: 'absolute',
                    title: 'Procedure Details',
                    items: [
                        {
                            xtype: 'combobox',
                            x: 15,
                            y: 30,
                            fieldLabel: 'Procedure Class',
                            name: 'procedure_class',
                            displayField: 'proc_class',
                            store: 'ProcedureClassStore',
                            valueField: 'ID'
                        },
                        {
                            xtype: 'combobox',
                            x: 270,
                            y: 30,
                            width: 90,
                            name: 'class_code',
                            displayField: 'class_value',
                            store: 'ClassCodes',
                            valueField: 'ID'
                        },
                        {
                            xtype: 'combobox',
                            x: 15,
                            y: 5,
                            width: 390,
                            fieldLabel: 'Diagnosis',
                            name: 'diagnosis',
                            hideTrigger: true,
                            displayField: 'description',
                            store: 'DiagnosisStore',
                            valueField: 'diagnosis_code'
                        },
                        {
                            xtype: 'timefield',
                            x: 15,
                            y: 55,
                            fieldLabel: 'OP Start Time',
                            name: 'op_starttime',
                            format: 'H:i:s'
                        },
                        {
                            xtype: 'timefield',
                            x: 15,
                            y: 80,
                            fieldLabel: 'OP End Time',
                            name: 'op_endtime',
                            format: 'H:i:s'
                        },
                        {
                            xtype: 'combobox',
                            x: 15,
                            y: 105,
                            fieldLabel: 'Operation Room',
                            name: 'op_room',
                            displayField: 'room_name',
                            store: 'TheatreRoomsStore',
                            valueField: 'room_no'
                        },
                        {
                            xtype: 'textfield',
                            x: 15,
                            y: 130,
                            width: 395,
                            fieldLabel: 'Scrub Nurse/Tech',
                            name: 'scrub_nurse'
                        }
                    ]
                },
                {
                    xtype: 'htmleditor',
                    anchor: '100%',
                    x: 0,
                    y: 420,
                    height: 150,
                    fieldLabel: 'Other Notes',
                    labelAlign: 'top',
                    name: 'notes'
                },
                {
                    xtype: 'button',
                    x: 520,
                    y: 250,
                    height: 40,
                    id: 'cmdSave',
                    width: 180,
                    text: 'Save Form'
                },
                {
                    xtype: 'button',
                    x: 520,
                    y: 300,
                    height: 50,
                    id: 'cmdClose',
                    width: 180,
                    text: 'Close'
                },
                {
                    xtype: 'combobox',
                    x: 420,
                    y: 170,
                    fieldLabel: 'Procedure Status',
                    name: 'status',
                    displayField: 'sname',
                    store: 'ProcedureStatusStore',
                    valueField: 'sname'
                },
                {
                    xtype: 'textfield',
                    x: 520,
                    y: 370,
                    hidden: true,
                    name: 'formStatus'
                },
                {
                    xtype: 'textfield',
                    x: 310,
                    y: 0,
                    id: 'encounter_nr',
                    width: 240,
                    fieldLabel: 'Encounter No',
                    labelWidth: 95,
                    name: 'encounter_nr',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 0,
                    fieldLabel: 'Booking No',
                    name: 'BookingNo',
                    readOnly: true
                }
            ]
        });

        me.callParent(arguments);
    }

});