/*
 * File: app/view/CheckListGrid.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Procedures.view.CheckListGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.checklistgrid',

    requires: [
        'Ext.grid.View',
        'Ext.grid.column.Action'
    ],

    minHeight: 600,
    minWidth: 1000,
    title: 'Surgical Safety Checklists',
    store: 'SurgicalChecklistStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'form_type',
                    text: 'Form_type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'pid',
                    text: 'Pid'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'encounter_nr',
                    text: 'Encounter_nr'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'procedure_date',
                    text: 'Procedure_date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'procedure_ID',
                    text: 'Procedure_ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'procedure_name',
                    text: 'Procedure_name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nurse_scrubs',
                    text: 'Nurse_scrubs'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'identity',
                    text: 'Identity'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'site',
                    text: 'Site'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'procedure_check',
                    text: 'Procedure_check'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'consent',
                    text: 'Consent'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'age',
                    text: 'Age'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'ID_bracelet',
                    text: 'ID_bracelet'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'site_marked',
                    text: 'Site_marked'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'bathed',
                    text: 'Bathed'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'scrubbed',
                    text: 'Scrubbed'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'allergy',
                    text: 'Allergy'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'allergy_name',
                    text: 'Allergy_name'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'blood_available',
                    text: 'Blood_available'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'xray',
                    text: 'Xray'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'HB',
                    text: 'HB'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'HCT',
                    text: 'HCT'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'weight',
                    text: 'Weight'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'solids_from',
                    text: 'Solids_from'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'liquids_from',
                    text: 'Liquids_from'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'pre_anaesthesia_eva',
                    text: 'Pre_anaesthesia_eva'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'medication_rs',
                    text: 'Medication_rs'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'antiobiotic_check',
                    text: 'Antiobiotic_check'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'antibiotic_given',
                    text: 'Antibiotic_given'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'BP',
                    text: 'BP'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'HR',
                    text: 'HR'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'RR',
                    text: 'RR'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'temp',
                    text: 'Temp'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'O2_sat',
                    text: 'O2_sat'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'other_vitals',
                    text: 'Other_vitals'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'PT_Voided',
                    text: 'PT_Voided'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'removal_extras',
                    text: 'Removal_extras'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'members_confirm',
                    text: 'Members_confirm'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'new_member',
                    text: 'New_member'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'antibiotic_prophy_60',
                    text: 'Antibiotic_prophy_60'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'antibiotic_reason',
                    text: 'Antibiotic_reason'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'surgeon_reviews',
                    text: 'Surgeon_reviews'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'anaesthesia_review',
                    text: 'Anaesthesia_review'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'nursing_review',
                    text: 'Nursing_review'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'instruments',
                    text: 'Instruments'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'throat_pack',
                    text: 'Throat_pack'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'speciment_label',
                    text: 'Speciment_label'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'equipment_problems',
                    text: 'Equipment_problems'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'final_review',
                    text: 'Final_review'
                },
                {
                    xtype: 'actioncolumn',
                    id: 'editList',
                    icon: '../../icons/list_go.png',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                console.log(record.get('procedure_name'));
                            },
                            altText: 'edit List',
                            icon: '../../icons/list_go.png',
                            tooltip: 'Edit Checklist Items'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});