/*
 * File: app/view/PatientDetails.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Procedures.view.PatientDetails', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patientdetails',

    requires: [
        'Ext.form.field.Text'
    ],

    frame: true,
    height: 132,
    width: 750,
    layout: 'absolute',
    bodyPadding: 10,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 10,
                    fieldLabel: 'PID',
                    labelAlign: 'right',
                    name: 'pid'
                },
                {
                    xtype: 'textfield',
                    x: 315,
                    y: 40,
                    width: 365,
                    fieldLabel: 'Procedure Type',
                    labelAlign: 'right',
                    name: 'procedure_type'
                },
                {
                    xtype: 'textfield',
                    x: 310,
                    y: 10,
                    fieldLabel: 'Booking No',
                    labelAlign: 'right',
                    name: 'BookingNo'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 40,
                    fieldLabel: 'Encounter No',
                    labelAlign: 'right',
                    name: 'encounter_nr'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 70,
                    width: 355,
                    fieldLabel: 'Patient Names',
                    labelAlign: 'right',
                    name: 'pnames'
                }
            ]
        });

        me.callParent(arguments);
    }

});