/*
 * File: app/view/Credit.js
 * Date: Sun Mar 01 2020 16:27:17 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inpatient.view.Credit', {
    extend: 'Ext.form.Panel',
    alias: 'widget.credit',

    requires: [
        'Inpatient.view.DebitViewModel1',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'credit'
    },
    draggable: true,
    itemId: 'credit',
    layout: 'absolute',
    bodyPadding: 10,
    bodyStyle: 'background:#1b5f87',
    title: 'Credit Patients',

    items: [
        {
            xtype: 'panel',
            x: 300,
            y: 140,
            draggable: true,
            height: 565,
            width: 825,
            bodyStyle: 'background:#84b3cc',
            title: 'Credits',
            items: [
                {
                    xtype: 'fieldset',
                    height: 130,
                    style: 'background-color: #d9f2e6;',
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 5,
                            width: 245,
                            fieldLabel: 'Patient No (PID)',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 120,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 25,
                            y: 40,
                            width: 225,
                            fieldLabel: 'Debit No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 305,
                            y: 40,
                            width: 210,
                            fieldLabel: 'Bill Number',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;'
                        },
                        {
                            xtype: 'textfield',
                            x: 285,
                            y: 75,
                            width: 230,
                            fieldLabel: 'Encounter No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 120
                        },
                        {
                            xtype: 'datefield',
                            x: 25,
                            y: 75,
                            width: 225,
                            fieldLabel: 'Date',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 250,
                            y: 5,
                            width: 265,
                            labelAlign: 'right',
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    frame: true,
                    height: 292,
                    store: 'DebitStore',
                    viewConfig: {
                        height: 142
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 78,
                            dataIndex: 'partcode',
                            text: 'Part Code'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 246,
                            dataIndex: 'item_description',
                            text: 'Description'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 184,
                            dataIndex: 'category',
                            text: 'Category'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'unit_price',
                            text: 'Price'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 55,
                            dataIndex: 'qty',
                            text: 'Qty'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Total',
                            text: 'Total'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 85,
                    style: 'background-color: #d9f2e6;',
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'button',
                            x: 520,
                            y: 40,
                            formBind: true,
                            height: 30,
                            width: 120,
                            iconCls: 'x-fa fa-save',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            x: 390,
                            y: 40,
                            height: 30,
                            width: 120,
                            iconCls: 'x-fa fa-trash',
                            text: 'Delete Row'
                        },
                        {
                            xtype: 'button',
                            x: 60,
                            y: 30,
                            height: 30,
                            itemId: 'cmdItemsList',
                            width: 120,
                            iconCls: 'x-fa fa-plus',
                            text: 'Get Items List'
                        },
                        {
                            xtype: 'button',
                            x: 660,
                            y: 40,
                            height: 30,
                            width: 120,
                            iconCls: 'x-fa fa-close',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'textfield',
                            x: 570,
                            y: 0,
                            fieldLabel: 'Total',
                            labelWidth: 50
                        }
                    ]
                }
            ]
        }
    ]

});