/*
 * File: app/view/Debit.js
 * Date: Tue Jul 14 2020 15:52:54 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inpatient.view.Debit', {
    extend: 'Ext.form.Panel',
    alias: 'widget.debit',

    requires: [
        'Inpatient.view.DebitViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.grid.filters.filter.String',
        'Ext.form.field.Number',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.filters.Filters',
        'Ext.selection.RowModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'debit'
    },
    itemId: 'debit',
    layout: 'absolute',
    bodyPadding: 10,
    bodyStyle: 'background:#1b5f87',
    title: 'Debit Patients',
    url: '../../data/getDataFunctions.php?task=saveDebit',

    items: [
        {
            xtype: 'form',
            x: 175,
            y: 75,
            draggable: true,
            frame: true,
            height: 565,
            itemId: 'debitsForm',
            padding: '0 0 0 0',
            width: 860,
            bodyStyle: 'background:#84b3cc',
            title: 'Debits',
            url: '../../data/getDataFunctions.php?task=saveDebit',
            items: [
                {
                    xtype: 'fieldset',
                    height: 112,
                    padding: '0 0 0 0',
                    style: 'background-color: #d9f2e6;',
                    width: 1258,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 5,
                            itemId: 'txtPid',
                            tabIndex: 1,
                            width: 250,
                            fieldLabel: 'PID',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'pid',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 40,
                            itemId: 'debitNo',
                            tabIndex: 2,
                            width: 250,
                            fieldLabel: 'Debit No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'debitdate',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 75,
                            itemId: 'debitDate',
                            tabIndex: 3,
                            width: 250,
                            fieldLabel: 'Date',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'debitdate',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 260,
                            y: 5,
                            id: 'pname',
                            itemId: 'pname',
                            width: 270,
                            name: 'pname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 280,
                            y: 75,
                            itemId: 'encounterNo',
                            width: 250,
                            fieldLabel: 'Encounter No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'pname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 280,
                            y: 40,
                            itemId: 'billNumber',
                            width: 250,
                            fieldLabel: 'Bill Number',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'pname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 600,
                            y: 15,
                            itemId: 'txtSource',
                            width: 130,
                            value: 'debit'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    reference: 'debitList',
                    frame: true,
                    height: 308,
                    itemId: 'itemsGrid',
                    margin: '0 0 0 0',
                    columnLines: true,
                    store: 'DebitStore',
                    viewConfig: {
                        height: 142,
                        tabIndex: 4
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'partcode',
                            text: 'Part Code',
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 307,
                            dataIndex: 'item_description',
                            text: 'Description',
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'category',
                            text: 'Category'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'unit_price',
                            text: 'Price'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'qty',
                            text: 'Qty',
                            editor: {
                                xtype: 'numberfield',
                                value: 1,
                                maxValue: 20,
                                minValue: 1
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var strSum=0;
                                store.getRange().forEach(function(rec) {
                                    // console.log(rec.get('unit_price'));
                                    strSum += (rec.get('unit_price')*rec.get('qty'));
                                    console.log(rec.get('strSum'));
                                } );
                                view.up('grid').up('panel').down('#txtTotal').setValue(strSum);

                                var totalPrice=record.get('unit_price')*record.get('qty');

                                return totalPrice;
                            },
                            dataIndex: 'Total',
                            text: 'Total'
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 1
                        },
                        {
                            ptype: 'gridfilters'
                        }
                    ],
                    selModel: {
                        selType: 'rowmodel',
                        mode: 'MULTI'
                    }
                },
                {
                    xtype: 'fieldset',
                    height: 88,
                    style: 'background-color: #d9f2e6;',
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'button',
                            x: 580,
                            y: 40,
                            formBind: true,
                            height: 30,
                            itemId: 'cmdSaveDebits',
                            width: 120,
                            iconCls: 'x-fa fa-save',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            x: 440,
                            y: 40,
                            height: 30,
                            itemId: 'cmdDeleteRow',
                            width: 120,
                            iconCls: 'x-fa fa-trash',
                            text: 'Romove Row'
                        },
                        {
                            xtype: 'button',
                            x: 710,
                            y: 40,
                            height: 30,
                            itemId: 'cmdClose',
                            width: 120,
                            iconCls: 'x-fa fa-close',
                            text: 'Close'
                        },
                        {
                            xtype: 'textfield',
                            x: 600,
                            y: 0,
                            itemId: 'txtTotal',
                            fieldLabel: 'Total',
                            labelWidth: 50,
                            value: 0
                        },
                        {
                            xtype: 'button',
                            x: 0,
                            y: 10,
                            height: 30,
                            itemId: 'cmdServiceList',
                            width: 130,
                            iconCls: 'x-fa fa-plus',
                            text: 'Get Items List'
                        },
                        {
                            xtype: 'button',
                            x: 312,
                            y: 4,
                            height: 33,
                            hidden: true,
                            itemId: 'cmdAddRow',
                            width: 89,
                            text: 'Add Row'
                        }
                    ]
                }
            ]
        }
    ]

});