/*
 * File: app/view/MainPanel.js
 * Date: Fri Mar 06 2020 14:11:55 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inpatient.view.MainPanel', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainpanel',

    requires: [
        'Inpatient.view.MainPanelViewModel',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'mainpanel'
    },
    layout: 'border',

    items: [
        {
            xtype: 'container',
            region: 'center',
            flex: 2,
            layout: 'fit',
            items: [
                {
                    xtype: 'panel',
                    title: 'Inpatients Dashboard'
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 0,
            region: 'west',
            width: 263,
            layout: 'accordion',
            header: {
                layout: {
                    align: 'stretchmax'
                },
                iconCls: 'x-fa fa-home',
                style: 'background:#1b5f87',
                title: {
                    text: 'Inpatients',
                    textAlign: 'center',
                    flex: 0,
                    minWidth: 160
                }
            },
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    ui: 'default-menubar',
                    bodyStyle: 'background:#5fa2dd; color:#ffff;!important;',
                    header: {
                        style: 'background:#1b5f87;color:white;font-weight:bold;'
                    },
                    title: 'Inpatient Activities',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'DashBoard',
                            text: 'Dashboard'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'WardOccupancy',
                            text: 'Ward Occupancy'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'Bills',
                            text: 'Bills Management'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'Debit',
                            text: 'Debit Patient'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'Credit',
                            text: 'Cedit Patient'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'NhifCredit',
                            text: 'NHIF Credit'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'InsuranceCredit',
                            text: 'Insurance Credit'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'FinaliseInvoice',
                            text: 'Finalize Invoice'
                        }
                    ]
                },
                {
                    xtype: 'menu',
                    floating: false,
                    bodyStyle: 'background:#5fa2dd;;color:white;',
                    header: {
                        style: 'background:#1b5f87;color:white;font-weight:bold;'
                    },
                    title: 'Inpatient Reports',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'InvoicePanel',
                            text: 'View Invoices'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'InvoicesList',
                            text: 'Pending Invoices'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'NhifCredits',
                            text: 'NHIF Credits'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'OccupancyList',
                            text: 'Bed Occupancy'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'AdmDis',
                            text: 'Admissions & Discharges'
                        }
                    ]
                },
                {
                    xtype: 'menu',
                    floating: false,
                    bodyStyle: 'background:#5fa2dd;;color:white;',
                    header: {
                        style: 'background:#1b5f87;color:white;font-weight:bold;'
                    },
                    title: 'Settings',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'InvoicePanel',
                            text: 'Wards Management'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'InvoicesList',
                            text: 'Pending Invoices'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'NhifCredits',
                            text: 'NHIF Credits'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'OccupancyList',
                            text: 'Bed Occupancy'
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'AdmDis',
                            text: 'Admissions & Discharges'
                        }
                    ]
                }
            ]
        }
    ]

});