/*
 * File: app/view/Main.js
 * Date: Thu Mar 25 2021 15:51:25 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inpatient.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'Inpatient.view.MainViewModel',
        'Inpatient.view.DashBoard',
        'Inpatient.view.WardOccupancy',
        'Inpatient.view.Bills',
        'Inpatient.view.Receipts',
        'Inpatient.view.Debit',
        'Inpatient.view.NhifCredit',
        'Inpatient.view.InsuranceCredit',
        'Inpatient.view.FinaliseInvoice',
        'Inpatient.view.InvoicePanel',
        'Ext.tab.Bar',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'main'
    },
    height: 800,
    collapsible: false,
    header: {
        layout: {
            align: 'stretchmax'
        },
        iconCls: 'x-fa fa-home',
        style: 'background:#1b5f87',
        title: {
            text: 'Inpatients',
            textAlign: 'left',
            flex: 0,
            minWidth: 160,
            height: 33
        }
    },
    headerPosition: 'left',
    titleCollapse: false,
    titleRotation: 0,
    activeTab: 0,
    tabBarHeaderPosition: 1,
    tabRotation: 0,

    tabBar: {
        xtype: 'tabbar',
        flex: 1,
        frame: false
    },
    items: [
        {
            xtype: 'dashboard'
        },
        {
            xtype: 'wardoccupancy'
        },
        {
            xtype: 'bills'
        },
        {
            xtype: 'receipts'
        },
        {
            xtype: 'debit'
        },
        {
            xtype: 'nhifcredit'
        },
        {
            xtype: 'insurancecredit'
        },
        {
            xtype: 'finaliseinvoice'
        },
        {
            xtype: 'invoicepanel',
            title: 'Invoices'
        }
    ]

});