/*
 * File: app/model/OrderDetails.js
 * Date: Fri Jun 05 2020 22:44:28 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pharmacy.model.OrderDetails', {
    extend: 'Ext.data.Model',
    alias: 'model.orderdetails',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'PartCode'
        },
        {
            name: 'Description'
        },
        {
            name: 'Unit_Qty'
        },
        {
            name: 'Purchasing_Unit'
        },
        {
            name: 'Qty'
        },
        {
            name: 'Qty_Issued'
        },
        {
            name: 'Balance'
        },
        {
            name: 'Qty_In_Store'
        },
        {
            name: 'TotalUnits'
        }
    ]
});