/*
 * File: app/store/ProcedureClassStore.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Procedures.store.ProcedureClassStore', {
    extend: 'Ext.data.Store',
    alias: 'store.procedureclassstore',

    requires: [
        'Procedures.model.ProcedureClass',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'Procedures.model.ProcedureClass',
            storeId: 'ProcedureClassStore',
            proxy: {
                type: 'ajax',
                url: '../data/getDataFunctions.php?task=getProcedureClass',
                reader: {
                    type: 'json',
                    root: 'procedureClass'
                }
            }
        }, cfg)]);
    }
});