/*
 * File: app/view/ServiceOrders.js
 * Date: Tue Feb 18 2020 18:41:01 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pharmacy.view.ServiceOrders', {
    extend: 'Ext.form.Panel',
    alias: 'widget.serviceorders',

    requires: [
        'Pharmacy.view.ServiceOrdersViewModel',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.grid.plugin.CellEditing',
        'Ext.form.field.Number',
        'Ext.selection.CellModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'serviceorders'
    },
    frame: true,
    height: 728,
    width: 926,
    layout: 'absolute',
    bodyPadding: 10,
    bodyStyle: 'background-color: #d9f2e6;',
    url: '../../data/getDataFunctions.php?task=serviceOrders',

    items: [
        {
            xtype: 'combobox',
            x: 15,
            y: 5,
            itemId: 'serviceStore',
            fieldLabel: 'Select Supplying Store',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            labelWidth: 150,
            name: 'SelectSupplyingStore',
            displayField: 'Description',
            minChars: 2,
            queryMode: 'local',
            store: 'LocationsStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'gridpanel',
            x: 5,
            y: 50,
            frame: true,
            height: 190,
            itemId: 'pendingOrders',
            columnLines: true,
            store: 'ServiceOrderStore',
            viewConfig: {
                frame: true,
                height: 146
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'gridcolumn',
                    width: 76,
                    dataIndex: 'time',
                    text: 'Time'
                },
                {
                    xtype: 'gridcolumn',
                    width: 66,
                    dataIndex: 'req_no',
                    text: 'Req No'
                },
                {
                    xtype: 'gridcolumn',
                    width: 90,
                    dataIndex: 'store',
                    text: 'Store'
                },
                {
                    xtype: 'gridcolumn',
                    width: 130,
                    dataIndex: 'store_desc',
                    text: 'Store Desc'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sup_storeid',
                    text: 'Sup Storeid'
                },
                {
                    xtype: 'gridcolumn',
                    width: 205,
                    dataIndex: 'sup_storedesc',
                    text: 'Sup Storedesc'
                },
                {
                    xtype: 'gridcolumn',
                    width: 69,
                    dataIndex: 'status',
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    width: 176,
                    dataIndex: 'input_user',
                    text: 'Input User'
                }
            ]
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 245,
            itemId: 'requisiondate',
            fieldLabel: 'Requision Date',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            labelWidth: 120,
            name: 'date'
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 350,
            itemId: 'supplyingstore',
            fieldLabel: 'Supplying Store',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            labelWidth: 120,
            name: 'sup_storedesc'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 315,
            itemId: 'status',
            fieldLabel: 'Status',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'status'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 280,
            itemId: 'Store',
            width: 345,
            fieldLabel: 'Ordering Store',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'store'
        },
        {
            xtype: 'textfield',
            x: 520,
            y: 245,
            itemId: 'requisionnumber',
            fieldLabel: 'Requision No.',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'req_no'
        },
        {
            xtype: 'textfield',
            x: 520,
            y: 350,
            itemId: 'issuedate',
            fieldLabel: 'Ordered by',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'input_user'
        },
        {
            xtype: 'textfield',
            x: 520,
            y: 315,
            itemId: 'issuetype',
            fieldLabel: 'Issue type',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'IssueType'
        },
        {
            xtype: 'textfield',
            x: 520,
            y: 280,
            itemId: 'issuenumber',
            fieldLabel: 'Issue No',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'IssueNumber'
        },
        {
            xtype: 'gridpanel',
            x: 5,
            y: 385,
            frame: true,
            height: 245,
            itemId: 'detailedOrder',
            columnLines: true,
            store: 'OrderDetailStore',
            plugins: [
                {
                    ptype: 'cellediting',
                    clicksToEdit: 1
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PartCode',
                    text: 'Item Id'
                },
                {
                    xtype: 'gridcolumn',
                    width: 190,
                    dataIndex: 'Description',
                    text: 'Item Desc'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Unit_Qty',
                    text: 'Unit Qty'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Purchasing_Unit',
                    text: 'Purchasing Unit'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Qty',
                    text: 'Qty'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Qty_Issued',
                    text: 'Qty Issued',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Balance',
                    text: 'Balance'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Qty_In_Store',
                    text: 'Qty In Store'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TotalUnits',
                    text: 'Total Units'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PartCode',
                    text: 'Item Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Description',
                    text: 'Item Desc'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Unit_Qty',
                    text: 'Unit Qty'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Purchasing_Unit',
                    text: 'Purchasing Unit'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Qty',
                    text: 'Qty'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Qty_Issued',
                    text: 'Qty Issued'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Balance',
                    text: 'Balance'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Qty_In_Store',
                    text: 'Qty In Store'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TotalUnits',
                    text: 'Total Units'
                }
            ],
            selModel: {
                selType: 'cellmodel'
            }
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 635,
            itemId: 'totalitemsordered',
            fieldLabel: 'Total Items Ordered',
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            labelWidth: 140,
            name: 'TotalItemsOrdered'
        },
        {
            xtype: 'button',
            x: 450,
            y: 635,
            itemId: 'cancelOrder',
            text: 'Cancel Order'
        },
        {
            xtype: 'button',
            x: 785,
            y: 635,
            itemId: 'serviceOrders',
            width: 115,
            text: 'Send'
        }
    ]

});