/*
 * File: app/model/PendingBills.js
 * Date: Thu Jul 30 2020 15:14:16 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inpatient.model.PendingBills', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'Pid'
        },
        {
            name: 'EncounterNo'
        },
        {
            name: 'Names'
        },
        {
            name: 'AdmissionDate'
        },
        {
            name: 'BillNumber'
        },
        {
            name: 'BedDays'
        },
        {
            name: 'Bill'
        },
        {
            name: 'Payment'
        },
        {
            name: 'Balance'
        },
        {
            name: 'PayementMode'
        }
    ]
});