/*
 * File: app/store/ReceiptsAllocateSt.js
 * Date: Mon Aug 16 2021 14:09:45 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Debtors.store.ReceiptsAllocateSt', {
    extend: 'Ext.data.Store',
    alias: 'store.receiptsallocatest',

    requires: [
        'Debtors.model.ReceiptsAllocate',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 700,
            storeId: 'ReceiptsAllocateSt',
            model: 'Debtors.model.ReceiptsAllocate',
            proxy: {
                type: 'ajax',
                url: './data/getDataFunctions.php?task=getUnallocatedReceipts',
                reader: {
                    type: 'json',
                    rootProperty: 'receiptsList'
                }
            }
        }, cfg)]);
    }
});