/*
 * File: app/store/ItemslistStore.js
 * Date: Tue Dec 03 2019 12:54:33 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pharmacy.store.ItemslistStore', {
    extend: 'Ext.data.Store',
    alias: 'store.itemsliststore',

    requires: [
        'Pharmacy.model.ItemsList',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 3000,
            storeId: 'ItemslistStore',
            autoLoad: true,
            model: 'Pharmacy.model.ItemsList',
            proxy: {
                type: 'ajax',
                url: '../../data/getDataFunctions.php?task=getItemsList&sParams=\'Drug_list\',\'medical-supplies\'',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});