/*
 * File: app/store/PatientDetailStore.js
 * Date: Thu Jan 30 2020 13:24:20 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pharmacy.store.PatientDetailStore', {
    extend: 'Ext.data.Store',
    alias: 'store.patientdetailstore',

    requires: [
        'Pharmacy.model.PatientDetails',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'PatientDetailStore',
            model: 'Pharmacy.model.PatientDetails',
            proxy: {
                type: 'ajax',
                url: '../../data/getDataFunctions.php?task=getPatientPresc',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});