/*
 * File: app/model/OrdersTemplate.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pharmacy.model.OrdersTemplate', {
    extend: 'Ext.data.Model',
    alias: 'model.orderstemplate',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'PartCode'
        },
        {
            name: 'Description'
        },
        {
            name: 'PurchasingUnit'
        },
        {
            name: 'Level'
        },
        {
            name: 'MonthlyUsage'
        },
        {
            name: 'ReorderLevel'
        }
    ]
});