/*
 * File: app/view/ProcessOrder.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Requisition.view.ProcessOrder', {
    extend: 'Ext.form.Panel',
    alias: 'widget.processorder',

    requires: [
        'Requisition.view.ProcessOrderViewModel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'processorder'
    },
    height: 263,
    width: 435,
    layout: 'absolute',
    bodyPadding: 10,

    items: [
        {
            xtype: 'textfield',
            x: 15,
            y: 65,
            itemId: 'requisitionDate',
            width: 340,
            fieldLabel: 'Requisition No'
        },
        {
            xtype: 'datefield',
            x: 15,
            y: 110,
            itemId: 'processDate',
            width: 340,
            fieldLabel: 'Date'
        },
        {
            xtype: 'combobox',
            x: 15,
            y: 155,
            width: 340,
            fieldLabel: 'Supplier',
            displayField: 'SupplierName',
            store: 'SupplierStore',
            typeAhead: true,
            valueField: 'SupplierCode'
        },
        {
            xtype: 'button',
            x: 165,
            y: 200,
            height: 35,
            itemId: 'cmdProcess',
            width: 125,
            text: 'Print'
        },
        {
            xtype: 'button',
            x: 15,
            y: 200,
            height: 35,
            itemId: 'cmdProcess1',
            width: 125,
            text: 'Process'
        },
        {
            xtype: 'button',
            x: 305,
            y: 200,
            height: 35,
            itemId: 'cmdClose',
            width: 115,
            text: 'Close'
        },
        {
            xtype: 'displayfield',
            x: 35,
            y: 5,
            shrinkWrap: 1,
            width: 360,
            value: 'This process will close the MEDS order template and generate LPO',
            fieldStyle: 'font-size: small;font-weight: bold;color: green;text-align:center'
        }
    ]

});