/*
 * File: app/view/HtnTreatmentRegister.js
 * Date: Mon Oct 22 2018 10:41:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.view.HtnTreatmentRegister', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.htntreatmentregister',

    requires: [
        'ReportsMain.view.HtnTreatmentRegisterViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'htntreatmentregister'
    },
    height: 605,
    title: 'HTN Treatment Register',
    columnLines: true,
    store: 'HtnTreatmentStore',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'Date',
            text: 'Date'
        },
        {
            xtype: 'gridcolumn',
            width: 193,
            dataIndex: 'PatientName',
            text: 'Patient Name'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'NationalID',
            text: 'National Id'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Dob',
            text: 'Dob'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Gender',
            text: 'Gender'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'MobileConsent',
            text: 'Mobile Consent'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Mobile',
            text: 'Mobile'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Location',
            text: 'Location'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'NewPatient',
            text: 'New Patient'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ReturningPatient',
            text: 'Returning Patient'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ReferredFrom',
            text: 'Referred From'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'BPInitialReading',
            text: 'Bpinitial Reading'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'BPFirstReading',
            text: 'Bpfirst Reading'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'BPSecondReading',
            text: 'Bpsecond Reading'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'NormalBP',
            text: 'Normal Bp'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'PreHypertensive',
            text: 'Pre Hypertensive'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Hypertensive',
            text: 'Hypertensive'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Weight',
            text: 'Weight'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Height',
            text: 'Height'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Diabetic',
            text: 'Diabetic'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Smoker',
            text: 'Smoker'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Alcohol',
            text: 'Alcohol'
        },
        {
            xtype: 'gridcolumn',
            width: 650,
            dataIndex: 'Medication',
            text: 'Medication'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'HtnTreatmentStore'
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            height: 41,
            items: [
                {
                    xtype: 'datefield',
                    itemId: 'StartDate',
                    fieldLabel: 'Start Date',
                    labelWidth: 70
                },
                {
                    xtype: 'datefield',
                    itemId: 'EndDate',
                    fieldLabel: 'End Date',
                    labelWidth: 70
                },
                {
                    xtype: 'combobox',
                    itemId: 'htnReportType',
                    width: 344,
                    fieldLabel: 'HTN Report Type',
                    labelWidth: 110
                },
                {
                    xtype: 'button',
                    itemId: 'cmdPreviewRegister',
                    width: 116,
                    text: 'Preview'
                },
                {
                    xtype: 'button',
                    itemId: 'cmdExportRegister',
                    width: 116,
                    text: 'Export'
                }
            ]
        }
    ]

});