/*
 * File: app/view/OutpatientInvoicesViewModel.js
 * Date: Mon Oct 22 2018 10:41:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.view.OutpatientInvoicesViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.outpatientinvoices',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        outpatientInvoices: {
            model: 'ReportsMain.model.OutpatientInvoices',
            data: [
                {
                    Pid: 'eligendi',
                    EncounterNo: 'consectetur',
                    Names: 'velit',
                    BillDate: 'voluptas',
                    BillNumber: 'quam',
                    Amount: 'aut',
                    PaymentMethod: 'fugit'
                },
                {
                    Pid: 'reprehenderit',
                    EncounterNo: 'sunt',
                    Names: 'non',
                    BillDate: 'et',
                    BillNumber: 'blanditiis',
                    Amount: 'sequi',
                    PaymentMethod: 'aut'
                },
                {
                    Pid: 'corrupti',
                    EncounterNo: 'libero',
                    Names: 'quas',
                    BillDate: 'molestiae',
                    BillNumber: 'vel',
                    Amount: 'voluptatum',
                    PaymentMethod: 'repellat'
                },
                {
                    Pid: 'veniam',
                    EncounterNo: 'nulla',
                    Names: 'in',
                    BillDate: 'voluptatem',
                    BillNumber: 'nisi',
                    Amount: 'provident',
                    PaymentMethod: 'quisquam'
                },
                {
                    Pid: 'quidem',
                    EncounterNo: 'odio',
                    Names: 'inventore',
                    BillDate: 'quas',
                    BillNumber: 'labore',
                    Amount: 'ut',
                    PaymentMethod: 'recusandae'
                },
                {
                    Pid: 'totam',
                    EncounterNo: 'qui',
                    Names: 'delectus',
                    BillDate: 'dignissimos',
                    BillNumber: 'dolorem',
                    Amount: 'voluptatem',
                    PaymentMethod: 'nihil'
                },
                {
                    Pid: 'aut',
                    EncounterNo: 'voluptatibus',
                    Names: 'est',
                    BillDate: 'autem',
                    BillNumber: 'itaque',
                    Amount: 'voluptatum',
                    PaymentMethod: 'voluptatum'
                },
                {
                    Pid: 'dolorem',
                    EncounterNo: 'voluptatum',
                    Names: 'cumque',
                    BillDate: 'nemo',
                    BillNumber: 'et',
                    Amount: 'tenetur',
                    PaymentMethod: 'ab'
                },
                {
                    Pid: 'saepe',
                    EncounterNo: 'voluptas',
                    Names: 'quas',
                    BillDate: 'quis',
                    BillNumber: 'qui',
                    Amount: 'dolore',
                    PaymentMethod: 'occaecati'
                },
                {
                    Pid: 'quod',
                    EncounterNo: 'quis',
                    Names: 'perferendis',
                    BillDate: 'animi',
                    BillNumber: 'consequatur',
                    Amount: 'omnis',
                    PaymentMethod: 'harum'
                },
                {
                    Pid: 'excepturi',
                    EncounterNo: 'temporibus',
                    Names: 'quas',
                    BillDate: 'ad',
                    BillNumber: 'eum',
                    Amount: 'autem',
                    PaymentMethod: 'non'
                },
                {
                    Pid: 'qui',
                    EncounterNo: 'rerum',
                    Names: 'repellat',
                    BillDate: 'vitae',
                    BillNumber: 'necessitatibus',
                    Amount: 'aperiam',
                    PaymentMethod: 'debitis'
                },
                {
                    Pid: 'neque',
                    EncounterNo: 'enim',
                    Names: 'mollitia',
                    BillDate: 'porro',
                    BillNumber: 'nam',
                    Amount: 'in',
                    PaymentMethod: 'qui'
                },
                {
                    Pid: 'hic',
                    EncounterNo: 'ut',
                    Names: 'beatae',
                    BillDate: 'quaerat',
                    BillNumber: 'doloremque',
                    Amount: 'beatae',
                    PaymentMethod: 'neque'
                },
                {
                    Pid: 'vel',
                    EncounterNo: 'quia',
                    Names: 'error',
                    BillDate: 'in',
                    BillNumber: 'iste',
                    Amount: 'ut',
                    PaymentMethod: 'eum'
                },
                {
                    Pid: 'qui',
                    EncounterNo: 'rerum',
                    Names: 'at',
                    BillDate: 'repudiandae',
                    BillNumber: 'numquam',
                    Amount: 'qui',
                    PaymentMethod: 'quod'
                },
                {
                    Pid: 'rerum',
                    EncounterNo: 'reiciendis',
                    Names: 'voluptas',
                    BillDate: 'tempora',
                    BillNumber: 'illum',
                    Amount: 'incidunt',
                    PaymentMethod: 'ut'
                },
                {
                    Pid: 'facilis',
                    EncounterNo: 'beatae',
                    Names: 'repudiandae',
                    BillDate: 'voluptas',
                    BillNumber: 'ad',
                    Amount: 'voluptas',
                    PaymentMethod: 'minima'
                },
                {
                    Pid: 'alias',
                    EncounterNo: 'molestiae',
                    Names: 'pariatur',
                    BillDate: 'magni',
                    BillNumber: 'eveniet',
                    Amount: 'modi',
                    PaymentMethod: 'quod'
                },
                {
                    Pid: 'provident',
                    EncounterNo: 'eum',
                    Names: 'molestias',
                    BillDate: 'quae',
                    BillNumber: 'eius',
                    Amount: 'nobis',
                    PaymentMethod: 'ut'
                },
                {
                    Pid: 'vel',
                    EncounterNo: 'quia',
                    Names: 'molestiae',
                    BillDate: 'minus',
                    BillNumber: 'perferendis',
                    Amount: 'non',
                    PaymentMethod: 'non'
                },
                {
                    Pid: 'in',
                    EncounterNo: 'ea',
                    Names: 'et',
                    BillDate: 'deleniti',
                    BillNumber: 'sit',
                    Amount: 'exercitationem',
                    PaymentMethod: 'saepe'
                },
                {
                    Pid: 'alias',
                    EncounterNo: 'qui',
                    Names: 'quia',
                    BillDate: 'asperiores',
                    BillNumber: 'est',
                    Amount: 'qui',
                    PaymentMethod: 'odit'
                },
                {
                    Pid: 'laborum',
                    EncounterNo: 'blanditiis',
                    Names: 'est',
                    BillDate: 'magni',
                    BillNumber: 'doloribus',
                    Amount: 'eum',
                    PaymentMethod: 'voluptatibus'
                },
                {
                    Pid: 'nihil',
                    EncounterNo: 'repudiandae',
                    Names: 'nesciunt',
                    BillDate: 'quaerat',
                    BillNumber: 'odit',
                    Amount: 'earum',
                    PaymentMethod: 'iure'
                },
                {
                    Pid: 'enim',
                    EncounterNo: 'in',
                    Names: 'magni',
                    BillDate: 'voluptas',
                    BillNumber: 'aut',
                    Amount: 'reprehenderit',
                    PaymentMethod: 'quia'
                },
                {
                    Pid: 'fugit',
                    EncounterNo: 'ipsum',
                    Names: 'magnam',
                    BillDate: 'quod',
                    BillNumber: 'natus',
                    Amount: 'et',
                    PaymentMethod: 'nobis'
                },
                {
                    Pid: 'cumque',
                    EncounterNo: 'quam',
                    Names: 'molestiae',
                    BillDate: 'sequi',
                    BillNumber: 'omnis',
                    Amount: 'reiciendis',
                    PaymentMethod: 'incidunt'
                },
                {
                    Pid: 'sit',
                    EncounterNo: 'quisquam',
                    Names: 'modi',
                    BillDate: 'iusto',
                    BillNumber: 'amet',
                    Amount: 'asperiores',
                    PaymentMethod: 'sed'
                },
                {
                    Pid: 'quidem',
                    EncounterNo: 'voluptate',
                    Names: 'dicta',
                    BillDate: 'voluptatibus',
                    BillNumber: 'itaque',
                    Amount: 'quia',
                    PaymentMethod: 'ad'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});