/*
 * File: app/model/Encounters.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hha.model.Encounters', {
    extend: 'Ext.data.Model',
    alias: 'model.encounters',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'PID'
        },
        {
            name: 'PatientName'
        },
        {
            name: 'EncounterNo'
        },
        {
            name: 'EncounterTime'
        },
        {
            name: 'Sex'
        },
        {
            name: 'DOB'
        },
        {
            name: 'ScreeningDate'
        },
        {
            name: 'MobileNumber'
        },
        {
            name: 'NationalID'
        },
        {
            name: 'UniqueID'
        },
        {
            name: 'County'
        },
        {
            name: 'Location'
        },
        {
            name: 'ClinicianName'
        },
        {
            name: 'FacilityID'
        },
        {
            name: 'FacilityName'
        },
        {
            name: 'ScreeningCode'
        },
        {
            name: 'ScreeningSite'
        },
        {
            name: 'BPInitial1'
        },
        {
            name: 'BPInitial2'
        },
        {
            name: 'Weight'
        },
        {
            name: 'Height'
        },
        {
            name: 'BMI'
        },
        {
            name: 'BPFirstReading1'
        },
        {
            name: 'BPFirstReading2'
        },
        {
            name: 'BPSecondReading1'
        },
        {
            name: 'BPSecondReading2'
        },
        {
            name: 'Normal'
        },
        {
            name: 'Pre_hypertensive'
        },
        {
            name: 'Hypertensive'
        },
        {
            name: 'ReturnPatient'
        },
        {
            name: 'Observations'
        },
        {
            name: 'LMP'
        },
        {
            name: 'DrugAllergies'
        },
        {
            name: 'AllergiesDetails'
        },
        {
            name: 'AdheringMedications'
        },
        {
            name: 'AdheringMedicationsDetails'
        },
        {
            name: 'MildHypertensionLife'
        },
        {
            name: 'MildHypertensionDiuretic'
        },
        {
            name: 'MildHypertensionCcbs'
        },
        {
            name: 'MildHypertensionOthers'
        },
        {
            name: 'ModerateHypetensionLife'
        },
        {
            name: 'ModerateHypetensionDiuretic'
        },
        {
            name: 'ModerateHypetensionCcbs'
        },
        {
            name: 'ModerateHypetensionOthers'
        },
        {
            name: 'ModerateHypetensionAce'
        },
        {
            name: 'FollowupPlan'
        },
        {
            name: 'Clinician'
        },
        {
            name: 'Designation'
        }
    ]
});