/*
 * File: app/view/EditResults.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab.view.EditResults', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.editresults',

    requires: [
        'Lab.view.EditResultsViewModel',
        'Lab.view.Patientlists',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.grid.feature.Grouping'
    ],

    viewModel: {
        type: 'editresults'
    },
    height: 741,
    itemId: 'EditResults',
    width: 1069,
    layout: 'absolute',
    title: 'Edit Laboratory Results',

    items: [
        {
            xtype: 'patientlists',
            frame: true,
            height: 690,
            margin: '0 10 0 0'
        },
        {
            xtype: 'gridpanel',
            x: 450,
            y: 175,
            height: 511,
            width: 620,
            title: 'results',
            columnLines: true,
            store: 'LabResultsStore',
            viewConfig: {
                width: 798
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PartCode',
                    text: 'Part Code'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 199,
                    dataIndex: 'TestName',
                    text: 'Test Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ResultName',
                    text: 'Result Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ResultsValue',
                    text: 'Results Value'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'LowerRange',
                    text: 'Lower Range'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'UpperRange',
                    text: 'Upper Range'
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 40,
                    width: 100,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'button',
                            x: 30,
                            y: 5,
                            itemId: 'cmdEditResults',
                            width: 135,
                            iconCls: 'x-fa fa-edit',
                            text: 'Edit Results'
                        },
                        {
                            xtype: 'textfield',
                            x: 190,
                            y: 5,
                            itemId: 'encNr',
                            width: 110,
                            emptyText: 'encNr'
                        },
                        {
                            xtype: 'textfield',
                            x: 305,
                            y: 5,
                            itemId: 'labNo',
                            width: 110,
                            emptyText: 'labNo'
                        }
                    ]
                }
            ],
            features: [
                {
                    ftype: 'grouping'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 450,
            y: 5,
            height: 165,
            itemId: 'resultsGrid',
            columnLines: true,
            store: 'PendingTestsStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'LabNo',
                    text: 'Lab No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EncounterNo',
                    text: 'Encounter No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Description',
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Notes',
                    text: 'Notes'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PartCode',
                    text: 'Part Code'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleCollectionTime',
                    text: 'Sample Collection Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleName',
                    text: 'Sample Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleCollectedBy',
                    text: 'Sample Collected By'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleReceivedTime',
                    text: 'Sample Received Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TestDoneby',
                    text: 'Test Doneby'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ResultsReceivedTime',
                    text: 'Results Received Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ResultsVerifiedTime',
                    text: 'Results Verified Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Verifiedby',
                    text: 'Verifiedby'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ApprovedBy',
                    text: 'Approved By'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ApprovedTime',
                    text: 'Approved Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TestStatus',
                    text: 'Test Status'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'InputType',
                    text: 'Input Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Label',
                    text: 'Label'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'LabNo',
                    text: 'Lab No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EncounterNo',
                    text: 'Encounter No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Description',
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Notes',
                    text: 'Notes'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PartCode',
                    text: 'Part Code'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleCollectionTime',
                    text: 'Sample Collection Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleName',
                    text: 'Sample Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleCollectedBy',
                    text: 'Sample Collected By'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SampleReceivedTime',
                    text: 'Sample Received Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TestDoneby',
                    text: 'Test Doneby'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ResultsReceivedTime',
                    text: 'Results Received Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ResultsVerifiedTime',
                    text: 'Results Verified Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Verifiedby',
                    text: 'Verifiedby'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ApprovedBy',
                    text: 'Approved By'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ApprovedTime',
                    text: 'Approved Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TestStatus',
                    text: 'Test Status'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'InputType',
                    text: 'Input Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Label',
                    text: 'Label'
                }
            ]
        }
    ]

});