/*
 * File: app/view/FullHaemogram.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab.view.FullHaemogram', {
    extend: 'Ext.form.Panel',
    alias: 'widget.fullhaemogram',

    requires: [
        'Lab.view.FullHaemogramViewModel',
        'Ext.form.field.Display',
        'Ext.form.FieldSet',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'fullhaemogram'
    },
    itemId: 'fullHaemogram',
    width: 544,
    bodyStyle: 'background:#629670;',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 30,
            width: 525,
            layout: 'absolute',
            items: [
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 0,
                    width: 215,
                    value: 'Full Haemogram',
                    fieldStyle: 'font-size: 14px;font-weight: bold;color: white;'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    frame: true,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'WBC',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-123'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Neu%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-124'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Lym%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-125'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Mon%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-126'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Eos%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-127'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Bas%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-128'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Neu#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-129'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Lym#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-130'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Mon#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-131'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Eos#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-132'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'Bas#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-133'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'RBC',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-134'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'HGB',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-135'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'HCT',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-136'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'MCV',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-137'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'MCH',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-138'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'MCHC',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-139'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'RDW-CV',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-140'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'RDW-SD',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-141'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'PLT',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-142'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'MPV',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-143'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'PDW',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-144'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: 'PCT',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-145'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: '* ALY%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-146'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: '*LIC%',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-147'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: '*ALY#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-148'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '0 0 3 0',
                            fieldLabel: '*LIC#',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'group-ltest70-149'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    width: 104,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_WBC'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Neu2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Lym2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Mon1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Eos1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Bas1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Neu2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Lym2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Mon2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Eos2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_Bas2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_RBC'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_HGB'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_HCT'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_MCV'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_MCH'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_MCHC'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_RDW-CV'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_RDW-SD'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_PLT'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_MPV'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_PDW'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_PCT'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_ALY1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_LIC1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_ALY2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 69,
                            name: 'lower_LIC2'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_WBC'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Neu1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Lym1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Mon1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Eos1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Bas1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Neu2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Lym2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Mon2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Mon2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_Bas2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_RBC'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_HGB'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_HCT'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_MCV'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_MCH'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_MCHC'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_RDW-CV'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_RDW-SD'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_PLT'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_MPV'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_PDW'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_PCT'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_ALY1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_LIC1'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_ALY2'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 3 0',
                            width: 71,
                            name: 'upper_LIC2'
                        }
                    ]
                }
            ]
        }
    ]

});