/*
 * File: app/view/PatientDetails.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab.view.PatientDetails', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.patientdetails',

    requires: [
        'Lab.view.PatientDetailsViewModel',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'patientdetails'
    },
    height: 90,
    layout: 'absolute',

    items: [
        {
            xtype: 'displayfield',
            x: 25,
            y: -1,
            itemId: 'pid',
            margin: 0,
            padding: 0,
            fieldLabel: 'Pid',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 260,
            y: -1,
            itemId: 'encounterno',
            fieldLabel: 'Encounter No',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 260,
            y: 60,
            itemId: 'paymode',
            fieldLabel: 'PaymentMethod',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 455,
            y: 20,
            itemId: 'labno',
            fieldLabel: 'Lab No',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 260,
            y: 20,
            itemId: 'priority',
            fieldLabel: 'Priority',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 260,
            y: 40,
            itemId: 'createid',
            fieldLabel: 'Requested By',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 25,
            y: 15,
            itemId: 'names',
            fieldLabel: 'Names',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 25,
            y: 35,
            itemId: 'dob',
            fieldLabel: 'Date of Birth',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 25,
            y: 55,
            itemId: 'sex',
            fieldLabel: 'Gender',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        },
        {
            xtype: 'displayfield',
            x: 455,
            y: 0,
            itemId: 'fileno',
            fieldLabel: 'Hospital File',
            labelStyle: 'font-size: 12px;font-weight: bold;color: green;',
            fieldStyle: 'font-size: 10px;font-weight: bold;color: red;'
        }
    ]

});