/*
 * File: app/store/OpMobidityStore.js
 * Date: Wed May 20 2020 15:42:19 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ReportsMain.store.OpMobidityStore', {
    extend: 'Ext.data.Store',
    alias: 'store.opmobiditystore',

    requires: [
        'ReportsMain.model.OpMobidityModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'OpMobidityStore',
            autoLoad: false,
            model: 'ReportsMain.model.OpMobidityModel',
            proxy: {
                type: 'ajax',
                url: 'data/getReportsData.php?task=mobidity',
                reader: {
                    type: 'json',
                    rootProperty: 'mobidity'
                }
            }
        }, cfg)]);
    }
});